line_length:
  warning: 750  # Set a warning when lines exceed 300 characters
type_body_length:
  warning: 500  # Set a warning when a type body exceeds 500 lines
file_length:
  warning: 750  # Set a warning when a file exceeds 750 lines

disabled_rules:
  - nesting
  - function_body_length
  - trailing_whitespace
  - redundant_string_enum_value
  - unused_closure_parameter


excluded:
  - .git
  - Pods
  - Carthage
